### ISSUE TITLE
Pivot tables

### ISSUE THREAD

**Issue by timcv** [michielkempen/nova-order-field#13]
Hi,

Dose this work on pivot tables for ManyToMany relationships?

//Tim

**Comment by gaelreyrol** [comment]
I have tested it and actually it does not 😕

**Comment by timcv** [comment]
Thank you!

**Comment by gaelreyrol** [comment]
@timcv Maybe you can let it opened ? In my opinion it should be resolved !

**Comment by toonvandenbos** [comment]
@timcv Yup, please re-open the issue :)

**Comment by timcv** [comment]
Ok, can do that.

**Comment by toonvandenbos** [comment]
FYI: I submitted a PR (#17) which adds pivot table support. Let's hope @michielkempen will be able to merge it soon  👍

**Comment by michielkempen** [comment]
I merged the PR of @Nyratas and tagged a new version 2.0.2 with support for Pivot Tables.

For documentation, please refer to the extensive explanation of Toon in #17.
