### ISSUE TITLE
Conflicting with App\Nova\Filter from 2.0.2

### ISSUE THREAD

**Issue by f-liva** [michielkempen/nova-order-field#18]
App\Nova\Filter and MichielKempen\NovaOrderField\Orderable define the same property ($defaultOrderField) in the composition of App\Nova\Filter. However, the definition differs and is considered incompatible. Class was composed

From 2.0.1

**Comment by michielkempen** [comment]
Thanks to @mbardelmeijer this problem is resolved in version 2.0.3.
