### ISSUE TITLE
Increment/decrement doesn't have into account prev/next list item

### ISSUE THREAD

**Issue by doriandigital** [michielkempen/nova-order-field#6]
Hi there,

Imagine the following scenario:

CATEGORIES
ID    Name    Order
1      Item1     1
2     Item2     2
3     Item3     3    -> Let's assume this item is deleted by the user
4     Item4     4

if you try to move Item4 up, above Item2, it will only increase its order value by 1, meaning it will still be the last element in the list, while the expected behavior would be to position it on top of Item2.

Shall the increment not take into account the previous and next item order?

Awesome package nevertheless! Much appreciated :)

**Comment by lorado** [comment]
Well, when I use arrows on index view to reorder items, I don't have your issue. The number of deleted item in order is missing, yes, but on reorder, items just switches numbers. 
As long reorder works, it doesn't matter, what are the numbers in DB =)
